/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "io/outputWriter/XYZWriter.h"

#include <iomanip>
#include <sstream>

using namespace mol_sim;

XYZWriter::XYZWriter() = default;

XYZWriter::~XYZWriter() = default;

void XYZWriter::plotParticles(ContainerRef particles, const std::string& filename, int iteration) {
  std::ofstream file;
  std::stringstream strstr;
  strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

  file.open(strstr.str().c_str());
  file << particles.size() << '\n';
  file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
          "file format doku."
       << '\n';

  for (auto& p : particles) {
    std::array<double, 3> x = p.getX();
    file << "Ar ";
    file.setf(std::ios_base::showpoint);

    for (auto& xi : x) {
      file << xi << " ";
    }

    file << '\n';
  }

  file.close();
}
