/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "particles/Particle.h"

#include <spdlog/spdlog.h>

#include <iostream>
#include <optional>

#include "utils/Vector.h"

using namespace mol_sim;

Particle::Particle(int type_arg)
    : x(R3{0., 0., 0.}),
      f(R3{0., 0., 0.}),
      epsilon(0.0),
      sigma(0.0),
      v(R3{0., 0., 0.}),
      m(0.0),
      old_x(R3{0., 0., 0.}),
      old_f(R3{0., 0., 0.}),
      type(type_arg),
      reference_position(R3{0., 0., 0.}),
      neighbors{std::nullopt, std::nullopt, std::nullopt, std::nullopt,
                std::nullopt, std::nullopt, std::nullopt, std::nullopt} {
    mirror_positions.reserve(4);  // Reserve space for up to 4 mirrors
    SPDLOG_DEBUG("Particle generated!");
}

Particle::Particle(const Particle& other) {
    x = other.x;
    v = other.v;
    f = other.f;
    epsilon = other.epsilon;
    sigma = other.sigma;
    old_x = other.old_x;
    old_f = other.old_f;
    m = other.m;
    type = other.type;
    mirror_locations = other.mirror_locations;
    neighbors.fill(std::nullopt);  // Don't copy neighbor indices - would break reciprocal relationships
    mirror_positions = other.mirror_positions;
    reference_position = other.reference_position;
    SPDLOG_DEBUG("Particle generated by copy!");
}

Particle& Particle::operator=(const Particle& other) {
    if (this == &other) {  // handle self-assignment
        return *this;
    }
    x = other.x;
    v = other.v;
    f = other.f;
    epsilon = other.epsilon;
    sigma = other.sigma;
    old_x = other.old_x;
    old_f = other.old_f;
    m = other.m;
    type = other.type;
    mirror_locations = other.mirror_locations;
    neighbors.fill(std::nullopt);  // Don't copy neighbor indices - would break reciprocal relationships
    mirror_positions = other.mirror_positions;
    reference_position = other.reference_position;
    SPDLOG_DEBUG("Particle assigned by copy!");
    return *this;
}

Particle::Particle(R3 x_arg, R3 v_arg, double m_arg, double epsilon_arg, double sigma_arg, int type_arg)
    : x(x_arg),
      f(R3(0., 0., 0.)),
      epsilon(epsilon_arg),
      sigma(sigma_arg),
      v(v_arg),
      m(m_arg),
      old_x(R3{0., 0., 0.}),
      old_f(R3{0., 0., 0.}),
      type(type_arg),
      reference_position(x_arg),
      neighbors{std::nullopt, std::nullopt, std::nullopt, std::nullopt,
                std::nullopt, std::nullopt, std::nullopt, std::nullopt} {
    mirror_positions.reserve(4);
    SPDLOG_DEBUG("Particle generated!");
}
Particle::Particle(R3 x_arg, R3 v_arg, R3 f_arg, double m_arg, double epsilon_arg, double sigma_arg, int type_arg)
    : x(x_arg),
      f(f_arg),
      epsilon(epsilon_arg),
      sigma(sigma_arg),
      v(v_arg),
      m(m_arg),
      old_x(R3{0., 0., 0.}),
      old_f(R3{0., 0., 0.}),
      type(type_arg),
      reference_position(x_arg),
      neighbors{std::nullopt, std::nullopt, std::nullopt, std::nullopt,
                std::nullopt, std::nullopt, std::nullopt, std::nullopt} {
    mirror_positions.reserve(4);
    SPDLOG_DEBUG("Particle generated!");
}

Particle::Particle(R3 x_arg, R3 old_x_arg, R3 v_arg, R3 f_arg, R3 old_f_arg, double m_arg, double epsilon_arg,
                   double sigma_arg, int type_arg)
    : x(x_arg),
      f(f_arg),
      epsilon(epsilon_arg),
      sigma(sigma_arg),
      v(v_arg),
      m(m_arg),
      old_x(old_x_arg),
      old_f(old_f_arg),
      type(type_arg),
      reference_position(x_arg),
      neighbors{std::nullopt, std::nullopt, std::nullopt, std::nullopt,
                std::nullopt, std::nullopt, std::nullopt, std::nullopt} {
    mirror_positions.reserve(4);
    SPDLOG_DEBUG("Particle generated!");
}

Particle::Particle(Particle&& other) noexcept {
    x = other.x;
    v = other.v;
    f = other.f;
    epsilon = other.epsilon;
    sigma = other.sigma;
    old_x = other.old_x;
    old_f = other.old_f;
    m = other.m;
    type = other.type;
    mirror_locations = other.mirror_locations;
    neighbors = other.neighbors;
    other.neighbors.fill(std::nullopt);
    SPDLOG_DEBUG("Particle generated by Move!");
}

Particle& Particle::operator=(Particle&& other) noexcept {
    if (this == &other) {
        return *this;
    }

    // Transfer scalar data
    x = other.x;
    v = other.v;
    f = other.f;
    epsilon = other.epsilon;
    sigma = other.sigma;
    old_x = other.old_x;
    old_f = other.old_f;
    m = other.m;
    type = other.type;
    mirror_locations = other.mirror_locations;

    // TRANSFER neighbors (Don't fill with nullopt!)
    neighbors = other.neighbors;

    // Clear the source's neighbors (Standard move semantics)
    other.neighbors.fill(std::nullopt);

    SPDLOG_DEBUG("Particle assigned by Move!");
    return *this;
}

Particle::~Particle() { SPDLOG_DEBUG("Particle destructed!"); }

std::string Particle::toString() const {
    std::stringstream stream;
    stream << "Particle: x:" << x << " old_x:" << old_x << " v: " << v << " f: " << f << " old_f: " << old_f
           << "epsilon: " << epsilon << "sigma:" << sigma << " type: " << type;
    return stream.str();
}

bool Particle::operator==(const Particle& other) const noexcept {
    return (x == other.x) and (old_x == other.old_x) and (v == other.v) and (f == other.f) and (type == other.type) and
           (m == other.m) and (old_f == other.old_f) and (epsilon == other.epsilon) and (sigma == other.sigma);
}

namespace mol_sim {
std::ostream& operator<<(std::ostream& stream, const Particle& p) {
    stream << p.toString();
    return stream;
}
}  // namespace mol_sim
