/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "particles/Particle.h"

#include <spdlog/spdlog.h>

#include <iostream>

#include "utils/Vector.h"

using namespace mol_sim;

Particle::Particle(int type_arg) {
    type = type_arg;
    SPDLOG_DEBUG("Particle generated!");
    f = {0., 0., 0.};
    old_f = {0., 0., 0.};
}

Particle::Particle(const Particle& other) {
    x = other.x;
    v = other.v;
    f = other.f;
    epsilon = other.epsilon;
    sigma = other.sigma;
    old_x = other.old_x;
    old_f = other.old_f;
    m = other.m;
    type = other.type;
    SPDLOG_DEBUG("Particle generated by copy!");
}

Particle& Particle::operator=(const Particle& other) {
    if (this == &other) {  // handle self-assignment
        return *this;
    }
    x = other.x;
    v = other.v;
    f = other.f;
    epsilon = other.epsilon;
    sigma = other.sigma;
    old_x = other.old_x;
    old_f = other.old_f;
    m = other.m;
    type = other.type;
    SPDLOG_DEBUG("Particle assigned by copy!");
    return *this;
}

Particle::Particle(R3 x_arg, R3 v_arg, double m_arg, double epsilon_arg, double sigma_arg, int type_arg)
    : x(x_arg),
      old_x(R3{0., 0., 0.}),
      v(v_arg),
      f(R3(0., 0., 0.)),
      old_f(R3{0., 0., 0.}),
      m(m_arg),
      epsilon(epsilon_arg),
      sigma(sigma_arg),
      type(type_arg) {
    SPDLOG_DEBUG("Particle generated!");
}
Particle::Particle(R3 x_arg, R3 v_arg, R3 f_arg, double m_arg, double epsilon_arg, double sigma_arg, int type_arg)
    : x(x_arg),
      old_x(R3{0., 0., 0.}),
      v(v_arg),
      f(f_arg),
      old_f(R3{0., 0., 0.}),
      m(m_arg),
      epsilon(epsilon_arg),
      sigma(sigma_arg),
      type(type_arg) {
    SPDLOG_DEBUG("Particle generated!");
}

Particle::Particle(R3 x_arg, R3 old_x_arg, R3 v_arg, R3 f_arg, R3 old_f_arg, double m_arg, double epsilon_arg,
                   double sigma_arg, int type_arg)
    : x(x_arg),
      old_x(old_x_arg),
      v(v_arg),
      f(f_arg),
      old_f(old_f_arg),
      m(m_arg),
      epsilon(epsilon_arg),
      sigma(sigma_arg),
      type(type_arg) {
    SPDLOG_DEBUG("Particle generated!");
}

Particle::~Particle() { SPDLOG_DEBUG("Particle destructed!"); }

const R3& Particle::getX() const noexcept { return x; }
R3& Particle::getX() noexcept { return x; }

const R3& Particle::getOldX() const noexcept { return old_x; }
R3& Particle::getOldX() noexcept { return old_x; }

const R3& Particle::getV() const noexcept { return v; }
R3& Particle::getV() noexcept { return v; }

const R3& Particle::getF() const noexcept { return f; }
R3& Particle::getF() noexcept { return f; }

const R3& Particle::getOldF() const noexcept { return old_f; }
R3& Particle::getOldF() noexcept { return old_f; }

double Particle::getM() const noexcept { return m; }

const int& Particle::getType() const noexcept { return type; }
int& Particle::getType() noexcept { return type; }

double Particle::getSigma() const noexcept { return sigma; }

double& Particle::getSigma() noexcept { return sigma; }

double Particle::getEpsilon() const noexcept { return epsilon; }

double& Particle::getEpsilon() noexcept { return epsilon; }

std::string Particle::toString() const {
    std::stringstream stream;
    stream << "Particle: x:" << x << " old_x:" << old_x << " v: " << v << " f: " << f << " old_f: " << old_f
           << "epsilon: " << epsilon << "sigma:" << sigma << " type: " << type;
    return stream.str();
}

bool Particle::operator==(const Particle& other) const noexcept {
    return (x == other.x) and (old_x == other.old_x) and (v == other.v) and (f == other.f) and (type == other.type) and
           (m == other.m) and (old_f == other.old_f) and (epsilon == other.epsilon) and (sigma == other.sigma);
}

namespace mol_sim {
std::ostream& operator<<(std::ostream& stream, const Particle& p) {
    stream << p.toString();
    return stream;
}
}  // namespace mol_sim
