/*
 * Particle.cpp
 *
 *  Created on: 23.02.2010
 *      Author: eckhardw
 */

#include "particles/Particle.h"

#include <iostream>

#include "utils/Logging.h"

using namespace mol_sim;

Particle::Particle(int type_arg) {
    type = type_arg;
    LOG_DEBUG("Particle generated!");
    f = {0., 0., 0.};
    old_f = {0., 0., 0.};
}

Particle::Particle(const Particle& other) {
    x = other.x;
    v = other.v;
    f = other.f;
    old_f = other.old_f;
    m = other.m;
    type = other.type;
    LOG_DEBUG("Particle generated by copy!");
}

// Todo: maybe use initializater list instead of copy?
Particle::Particle(R3 x_arg, R3 v_arg, double m_arg, int type_arg) {
    x = x_arg;
    v = v_arg;
    m = m_arg;
    type = type_arg;
    f = {0., 0., 0.};
    old_f = {0., 0., 0.};
    LOG_DEBUG("Particle generated!");
}

Particle::~Particle() { LOG_DEBUG("Particle destructed!"); }

const R3& Particle::getX() const { return x; }
R3& Particle::getX() { return x; }

const R3& Particle::getV() const { return v; }
R3& Particle::getV() { return v; }

const R3& Particle::getF() const { return f; }
R3& Particle::getF() { return f; }

const R3& Particle::getOldF() const { return old_f; }
R3& Particle::getOldF() { return old_f; }

double Particle::getM() const { return m; }

int Particle::getType() const { return type; }

std::string Particle::toString() const {
    std::stringstream stream;
    stream << "Particle: X:" << x << " v: " << v << " f: " << f << " old_f: " << old_f << " type: " << type;
    return stream.str();
}

bool Particle::operator==(const Particle& other) const {
    return (x == other.x) and (v == other.v) and (f == other.f) and (type == other.type) and (m == other.m) and
           (old_f == other.old_f);
}

std::ostream& operator<<(std::ostream& stream, Particle& p) {
    stream << p.toString();
    return stream;
}
