name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  - pull_request:
    branches: [ "main" ]
  - workflow_dispatch:
    inputs:
      branch:
        description: 'Select a branch'
        required: true
        type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

