name: Coverage Upload

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  upload-codecov:
    runs-on: mini-arc-runner-set
    container:
      image: mbichmann/molsim-vtk

    steps:
    - name: hash
      run: echo "Hello World"